export enum AuditAction {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_CANCELLED = 'TICKET_CANCELLED',
  TICKET_CHECKED_OUT = 'TICKET_CHECKED_OUT',
  PRICE_OVERRIDE = 'PRICE_OVERRIDE',
  CASH_CUT_OPENED = 'CASH_CUT_OPENED',
  CASH_CUT_CLOSED = 'CASH_CUT_CLOSED',
  USER_CREATED = 'USER_CREATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_DEACTIVATED = 'BRANCH_DEACTIVATED',
  PRICING_CONFIG_UPDATED = 'PRICING_CONFIG_UPDATED',
}
